apiVersion: v1
kind: ConfigMap
metadata:
  name: homework01
  namespace: homework
data:
  default: |
    server {
      listen       80;
      server_name  localhost;
      location / {
        root   /homework;
        index  index.html index.htm;
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: homework01
  namespace: homework
spec:
  containers:
  - name: nginx
    image: docker.angie.software/angie:latest
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","rm /homework/index.html"]
    ports:
    - containerPort: 80
      hostPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: "/homework"
    - name: config
      mountPath: "/etc/angie/http.d/"
# These containers are run during pod initialization
  initContainers:
  - name: install
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - echo "<html><title>Homework 01</title><body><h1>Hello world!</h1></body></html>" > /init/index.html
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}
  - name: config
    configMap:
      name: homework01
      items:
      - key: "default"
        path: "default.conf"
